services:

  vpn:
    build: ./vpn/
    container_name: vpn
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
      - "${DICOM_LISTENER_PORT}:${DICOM_LISTENER_PORT}"
    environment:
      - SERVER_ADDRESS
      - TZ
    cap_add:
      - net_admin
    volumes:
      - ./vpn/config:/vpn
    restart: unless-stopped

  db:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_RANDOM_ROOT_PASSWORD
      - TZ
    
  app:
    build: .
    container_name: petfectior-client
    depends_on:
      - db
      - vpn
    network_mode: service:vpn
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    volumes:
      - app_images:/home/petfectior/incoming
      - app_logs:${LOGGING_FILEPATH}
    restart: unless-stopped
    env_file:
      - .env

volumes:
  mysql_data:
  app_images:
  app_logs:
