version: "3.8"
services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_RANDOM_ROOT_PASSWORD
    
  app:
    build: .
    container_name: petfectior-client
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - label:disable      
    depends_on:
      - db
    ports:
      - 8000:8000
      - 11115:11115
    env_file:
      - .env
    volumes:
      - app_images:/home/petfectior/incoming

volumes:
  mysql_data:
  app_images:
