"""Added column created_by_user to device

Revision ID: 02bf4790f761
Revises: 31388f9ee3cf
Create Date: 2023-08-09 21:09:13.117913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02bf4790f761'
down_revision = '31388f9ee3cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('created_by_user')

    # ### end Alembic commands ###
