"""Changed state to step_state

Revision ID: 0f170fc03e91
Revises: 34b90a7c1209
Create Date: 2023-08-10 19:36:43.372171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f170fc03e91'
down_revision = '34b90a7c1209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step_state', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_task_state')
        batch_op.create_index(batch_op.f('ix_task_step_state'), ['step_state'], unique=False)
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_task_step_state'))
        batch_op.create_index('ix_task_state', ['state'], unique=False)
        batch_op.drop_column('step_state')

    # ### end Alembic commands ###
