"""Changed some data types in patient table

Revision ID: 1740f8eea54c
Revises: 62328cd33b87
Create Date: 2024-07-24 15:12:53.745588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1740f8eea54c'
down_revision = '62328cd33b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index('ix_series_SeriesTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index('ix_series_SeriesTime', ['SeriesTime'], unique=False)

    # ### end Alembic commands ###
