"""Added current step to Task table

Revision ID: 1825c679e794
Revises: 924e2d9b4be8
Create Date: 2023-08-09 09:14:47.126213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1825c679e794'
down_revision = '924e2d9b4be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_step', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('current_step_filename', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_current_step_filename'), ['current_step_filename'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_current_step_filename'))
        batch_op.drop_column('current_step_filename')
        batch_op.drop_column('current_step')

    # ### end Alembic commands ###
