"""Moved patient weight, age and size from patient to study

Revision ID: 2049032dc772
Revises: 1740f8eea54c
Create Date: 2024-07-25 11:19:53.142651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2049032dc772'
down_revision = '1740f8eea54c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('PatientWeight')
        batch_op.drop_column('PatientAge')
        batch_op.drop_column('PatientSize')

    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PatientWeight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('PatientAge', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('PatientSize', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.drop_column('PatientSize')
        batch_op.drop_column('PatientAge')
        batch_op.drop_column('PatientWeight')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PatientSize', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('PatientAge', sa.VARCHAR(length=4), nullable=True))
        batch_op.add_column(sa.Column('PatientWeight', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
