"""Created table for pet models names

Revision ID: 25e3a7ce6892
Revises: d2db1d8bcbf3
Create Date: 2024-03-18 18:31:13.980275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e3a7ce6892'
down_revision = 'd2db1d8bcbf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_model',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_pet_model'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_model')
    # ### end Alembic commands ###
