"""Renamed some columns in AppConfig

Revision ID: 281982dbeb1f
Revises: b4670bb7a2ea
Create Date: 2023-08-11 21:03:11.436162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281982dbeb1f'
down_revision = 'b4670bb7a2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_dir', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('unzip_dir', sa.String(length=128), nullable=True))
        batch_op.drop_column('packed_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packed_path', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('unzip_dir')
        batch_op.drop_column('zip_dir')

    # ### end Alembic commands ###
