"""Added state column to Task

Revision ID: 2857eeb21597
Revises: 872fdf527acb
Create Date: 2023-08-10 00:26:22.701263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2857eeb21597'
down_revision = '872fdf527acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_state'))
        batch_op.drop_column('state')

    # ### end Alembic commands ###
