"""Just testing

Revision ID: 31388f9ee3cf
Revises: c9d94c96760c
Create Date: 2023-08-09 20:36:06.294730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31388f9ee3cf'
down_revision = 'c9d94c96760c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_task',
    sa.Column('source_addr', sa.VARCHAR(length=16), nullable=True),
    sa.Column('source_aet', sa.VARCHAR(length=16), nullable=True),
    sa.Column('started', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('series', sa.VARCHAR(length=64), nullable=True),
    sa.Column('current_step', sa.VARCHAR(length=32), nullable=True),
    sa.Column('current_step_filename', sa.TEXT(), nullable=True),
    sa.Column('status_msg', sa.TEXT(), nullable=True),
    sa.Column('expected_imgs', sa.INTEGER(), nullable=True),
    sa.Column('task_id', sa.VARCHAR(length=18), nullable=False),
    sa.ForeignKeyConstraint(['series'], ['series.SeriesInstanceUID'], )
    )
    # ### end Alembic commands ###
