"""Added a current_step_data column of type text to keep the step data as serialized JSON

Revision ID: 34b90a7c1209
Revises: 2857eeb21597
Create Date: 2023-08-10 19:33:28.507856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b90a7c1209'
down_revision = '2857eeb21597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_step_data', sa.Text(), nullable=True))
        batch_op.drop_column('current_step_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_step_filename', sa.TEXT(), nullable=True))
        batch_op.drop_column('current_step_data')

    # ### end Alembic commands ###
