"""empty message

Revision ID: 3542775c250b
Revises: bea720428138
Create Date: 2023-08-14 14:20:27.770529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3542775c250b'
down_revision = 'bea720428138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('min_instances_in_series', sa.Integer(), nullable=True),
    sa.Column('slice_gap_tolerance', sa.Float(), nullable=True),
    sa.Column('series_timeout', sa.Integer(), nullable=True),
    sa.Column('store_scp_port', sa.Integer(), nullable=True),
    sa.Column('store_scp_aet', sa.String(length=64), nullable=True),
    sa.Column('mirror_mode', sa.Boolean(), nullable=True),
    sa.Column('server_url', sa.String(length=64), nullable=True),
    sa.Column('shared_path', sa.String(length=128), nullable=True),
    sa.Column('shared_mount_point', sa.String(length=128), nullable=True),
    sa.Column('zip_dir', sa.String(length=128), nullable=True),
    sa.Column('unzip_dir', sa.String(length=128), nullable=True),
    sa.Column('download_path', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('client_id', name=op.f('pk_app_config'))
    )
    op.create_table('source',
    sa.Column('identifier', sa.String(length=96), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('identifier', name=op.f('pk_source'))
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.alter_column('ae_title',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
        batch_op.alter_column('port',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_by_user')

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('originating_task', sa.String(length=18), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_series_originating_task_task'), 'task', ['originating_task'], ['id'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recon_settings', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('step_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=96), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_step_state'), ['step_state'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_task_source_source'), 'source', ['source'], ['identifier'])
        batch_op.drop_column('source_aet')
        batch_op.drop_column('current_step_filename')
        batch_op.drop_column('source_addr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_addr', sa.VARCHAR(length=16), nullable=True))
        batch_op.add_column(sa.Column('current_step_filename', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('source_aet', sa.VARCHAR(length=16), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_task_source_source'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_task_step_state'))
        batch_op.drop_column('source')
        batch_op.drop_column('step_state')
        batch_op.drop_column('recon_settings')

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_series_originating_task_task'), type_='foreignkey')
        batch_op.drop_column('originating_task')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('port',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
        batch_op.alter_column('ae_title',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    op.drop_table('source')
    op.drop_table('app_config')
    # ### end Alembic commands ###
