"""Added Source table and relationship wit Task

Revision ID: 38d8ca6878d8
Revises: bea720428138
Create Date: 2023-08-10 00:09:14.059449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d8ca6878d8'
down_revision = 'bea720428138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_device')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.alter_column('ae_title',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
        batch_op.alter_column('port',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_by_user')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=96), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_task_source_source'), 'source', ['source'], ['identifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_source_source'), type_='foreignkey')
        batch_op.drop_column('source')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('port',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
        batch_op.alter_column('ae_title',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    op.create_table('_alembic_tmp_device',
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('ae_title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('address', sa.VARCHAR(length=16), nullable=False),
    sa.Column('port', sa.INTEGER(), nullable=False),
    sa.Column('is_destination', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###
