"""Added server and shared path to AppConfig table

Revision ID: 390806ceaf3b
Revises: 915419325ee9
Create Date: 2023-08-11 12:16:22.452286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390806ceaf3b'
down_revision = '915419325ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server_url', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('shared_path', sa.String(length=128), nullable=True))
        batch_op.alter_column('client_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('client_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('shared_path')
        batch_op.drop_column('server_url')

    # ### end Alembic commands ###
