"""Task-RF relationship

Revision ID: 417bd525279d
Revises: 970e0005b769
Create Date: 2024-08-22 16:40:00.931201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417bd525279d'
down_revision = '970e0005b769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radiopharmaceutical', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_task_radiopharmaceutical_radiopharmaceutical'), 'radiopharmaceutical', ['radiopharmaceutical'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_radiopharmaceutical_radiopharmaceutical'), type_='foreignkey')
        batch_op.drop_column('radiopharmaceutical')

    # ### end Alembic commands ###
