"""Added shared_mount_point to AppConfig

Revision ID: 43b54d4423da
Revises: 42e38a26cf52
Create Date: 2023-08-11 18:14:24.555298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b54d4423da'
down_revision = '42e38a26cf52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_mount_point', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_column('shared_mount_point')

    # ### end Alembic commands ###
