"""Added full_status_msg to Task

Revision ID: 4a48dfc9f1dc
Revises: c2ceba845902
Create Date: 2024-08-19 13:20:27.080870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a48dfc9f1dc'
down_revision = 'c2ceba845902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_status_msg', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('full_status_msg')

    # ### end Alembic commands ###
