"""empty message

Revision ID: 52ff014b5384
Revises: 8c0ca16f4985
Create Date: 2024-03-05 09:18:15.014481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ff014b5384'
down_revision = '8c0ca16f4985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fwhm', sa.Float(), nullable=True),
    sa.Column('suffix', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filter_settings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filter_settings')
    # ### end Alembic commands ###
