"""Added AppConfig table

Revision ID: 568c9a36db9c
Revises: 0f170fc03e91
Create Date: 2023-08-10 20:15:47.080883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568c9a36db9c'
down_revision = '0f170fc03e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_instances_in_series', sa.Integer(), nullable=True),
    sa.Column('slice_gap_tolerance', sa.Float(), nullable=True),
    sa.Column('store_scp_port', sa.Integer(), nullable=True),
    sa.Column('store_scp_aet', sa.String(length=64), nullable=True),
    sa.Column('mirror_mode', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_config'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_config')
    # ### end Alembic commands ###
