"""Renamed column

Revision ID: 61ca043e4b0e
Revises: 43b54d4423da
Create Date: 2023-08-11 18:38:45.152569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ca043e4b0e'
down_revision = '43b54d4423da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recon_settings', sa.Text(), nullable=True))
        batch_op.drop_column('current_step_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_step_data', sa.TEXT(), nullable=True))
        batch_op.drop_column('recon_settings')

    # ### end Alembic commands ###
