"""Added fields from issue #33 to patient and series tables

Revision ID: 62328cd33b87
Revises: 2a41da30e667
Create Date: 2024-07-24 14:01:30.353362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62328cd33b87'
down_revision = '2a41da30e667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PatientWeight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('PatientAge', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('PatientSize', sa.Float(), nullable=True))

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SeriesNumber', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('SeriesTime', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_series_SeriesTime'), ['SeriesTime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_SeriesTime'))
        batch_op.drop_column('SeriesTime')
        batch_op.drop_column('SeriesNumber')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('PatientSize')
        batch_op.drop_column('PatientAge')
        batch_op.drop_column('PatientWeight')

    # ### end Alembic commands ###
