"""Changed series naming convention

Revision ID: 6a0a3cd26016
Revises: 52ff014b5384
Create Date: 2024-03-05 13:55:55.854721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0a3cd26016'
down_revision = '52ff014b5384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('mode', sa.String(length=32), nullable=True))
        batch_op.drop_column('suffix')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suffix', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('mode')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
