"""Removed source address and port from Task, as it is now in the Source table

Revision ID: 872fdf527acb
Revises: 38d8ca6878d8
Create Date: 2023-08-10 00:11:52.601126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872fdf527acb'
down_revision = '38d8ca6878d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('source_addr')
        batch_op.drop_column('source_aet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_aet', sa.VARCHAR(length=16), nullable=True))
        batch_op.add_column(sa.Column('source_addr', sa.VARCHAR(length=16), nullable=True))

    # ### end Alembic commands ###
