"""Update AppConfig

Revision ID: 915419325ee9
Revises: 568c9a36db9c
Create Date: 2023-08-10 20:51:28.037402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915419325ee9'
down_revision = '568c9a36db9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_timeout', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_column('series_timeout')

    # ### end Alembic commands ###
