"""Added radiopharmaceutical column to FilterSettings

Revision ID: 970e0005b769
Revises: c4bf16778663
Create Date: 2024-08-22 14:46:37.854862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970e0005b769'
down_revision = 'c4bf16778663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radiopharmaceutical', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter_settings', schema=None) as batch_op:
        batch_op.drop_column('radiopharmaceutical')

    # ### end Alembic commands ###
