"""Initializing database with AppLog table

Revision ID: 993882b43483
Revises: 
Create Date: 2023-08-01 16:23:46.833170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993882b43483'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('function', sa.String(length=64), nullable=True),
    sa.Column('msg', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_log_function'), ['function'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_log_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_log_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_log_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_app_log_module'))
        batch_op.drop_index(batch_op.f('ix_app_log_level'))
        batch_op.drop_index(batch_op.f('ix_app_log_function'))

    op.drop_table('app_log')
    # ### end Alembic commands ###
