"""Restarted without table relationships

Revision ID: ae821ec1d017
Revises: 
Create Date: 2023-08-17 10:16:17.603627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae821ec1d017'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('min_instances_in_series', sa.Integer(), nullable=True),
    sa.Column('slice_gap_tolerance', sa.Float(), nullable=True),
    sa.Column('series_timeout', sa.Integer(), nullable=True),
    sa.Column('store_scp_port', sa.Integer(), nullable=True),
    sa.Column('store_scp_aet', sa.String(length=64), nullable=True),
    sa.Column('mirror_mode', sa.Boolean(), nullable=True),
    sa.Column('server_url', sa.String(length=64), nullable=True),
    sa.Column('shared_path', sa.String(length=128), nullable=True),
    sa.Column('shared_mount_point', sa.String(length=128), nullable=True),
    sa.Column('zip_dir', sa.String(length=128), nullable=True),
    sa.Column('unzip_dir', sa.String(length=128), nullable=True),
    sa.Column('download_path', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('client_id', name=op.f('pk_app_config'))
    )
    op.create_table('app_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('function', sa.String(length=64), nullable=True),
    sa.Column('msg', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_log'))
    )
    with op.batch_alter_table('app_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_log_function'), ['function'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_log_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_log_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('device',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ae_title', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=16), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('is_destination', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_device'))
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_ae_title'), ['ae_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_port'), ['port'], unique=False)

    op.create_table('instance',
    sa.Column('SOPInstanceUID', sa.String(length=64), nullable=False),
    sa.Column('SOPClassUID', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('SOPInstanceUID', name=op.f('pk_instance'))
    )
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instance_SOPClassUID'), ['SOPClassUID'], unique=False)

    op.create_table('patient',
    sa.Column('PatientID', sa.String(length=64), nullable=False),
    sa.Column('PatientName', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('PatientID', name=op.f('pk_patient'))
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_PatientName'), ['PatientName'], unique=False)

    op.create_table('series',
    sa.Column('SeriesInstanceUID', sa.String(length=64), nullable=False),
    sa.Column('SeriesDate', sa.DateTime(), nullable=True),
    sa.Column('SeriesDescription', sa.String(length=64), nullable=True),
    sa.Column('Modality', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('SeriesInstanceUID', name=op.f('pk_series'))
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_Modality'), ['Modality'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_SeriesDate'), ['SeriesDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_SeriesDescription'), ['SeriesDescription'], unique=False)

    op.create_table('source',
    sa.Column('identifier', sa.String(length=96), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('identifier', name=op.f('pk_source'))
    )
    op.create_table('study',
    sa.Column('StudyInstanceUID', sa.String(length=64), nullable=False),
    sa.Column('StudyDate', sa.DateTime(), nullable=True),
    sa.Column('StudyDescription', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('StudyInstanceUID', name=op.f('pk_study'))
    )
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_StudyDate'), ['StudyDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_StudyDescription'), ['StudyDescription'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.String(length=18), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('current_step', sa.String(length=32), nullable=True),
    sa.Column('recon_settings', sa.Text(), nullable=True),
    sa.Column('step_state', sa.Integer(), nullable=True),
    sa.Column('status_msg', sa.Text(), nullable=True),
    sa.Column('expected_imgs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_step_state'), ['step_state'], unique=False)

    op.create_table('task_destination',
    sa.Column('task_id', sa.String(length=18), nullable=True),
    sa.Column('device_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['device_name'], ['device.name'], name=op.f('fk_task_destination_device_name_device')),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_task_destination_task_id_task'))
    )
    op.create_table('task_instance',
    sa.Column('task_id', sa.String(length=18), nullable=True),
    sa.Column('sop_instance_uid', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['sop_instance_uid'], ['instance.SOPInstanceUID'], name=op.f('fk_task_instance_sop_instance_uid_instance')),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_task_instance_task_id_task'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_instance')
    op.drop_table('task_destination')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_step_state'))

    op.drop_table('task')
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_StudyDescription'))
        batch_op.drop_index(batch_op.f('ix_study_StudyDate'))

    op.drop_table('study')
    op.drop_table('source')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_SeriesDescription'))
        batch_op.drop_index(batch_op.f('ix_series_SeriesDate'))
        batch_op.drop_index(batch_op.f('ix_series_Modality'))

    op.drop_table('series')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_PatientName'))

    op.drop_table('patient')
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instance_SOPClassUID'))

    op.drop_table('instance')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_port'))
        batch_op.drop_index(batch_op.f('ix_device_ae_title'))
        batch_op.drop_index(batch_op.f('ix_device_address'))

    op.drop_table('device')
    with op.batch_alter_table('app_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_app_log_module'))
        batch_op.drop_index(batch_op.f('ix_app_log_level'))
        batch_op.drop_index(batch_op.f('ix_app_log_function'))

    op.drop_table('app_log')
    op.drop_table('app_config')
    # ### end Alembic commands ###
