"""Added a many-to-many relationship between Task and Instance

Revision ID: b1af1f6a71f6
Revises: 1825c679e794
Create Date: 2023-08-09 17:09:30.345152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1af1f6a71f6'
down_revision = '1825c679e794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_instance',
    sa.Column('task_id', sa.String(length=18), nullable=True),
    sa.Column('sop_instance_uid', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['sop_instance_uid'], ['instance.SOPInstanceUID'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_instance')
    # ### end Alembic commands ###
