"""Added download_path

Revision ID: b4670bb7a2ea
Revises: 61ca043e4b0e
Create Date: 2023-08-11 19:17:30.465174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4670bb7a2ea'
down_revision = '61ca043e4b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_path', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_column('download_path')

    # ### end Alembic commands ###
