"""Reinitialized from scratch

Revision ID: bea720428138
Revises: 
Create Date: 2023-08-10 00:01:01.683460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea720428138'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('function', sa.String(length=64), nullable=True),
    sa.Column('msg', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_log_function'), ['function'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_log_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_log_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('device',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ae_title', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=16), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('is_destination', sa.Boolean(), nullable=True),
    sa.Column('created_by_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_ae_title'), ['ae_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_port'), ['port'], unique=False)

    op.create_table('patient',
    sa.Column('PatientID', sa.String(length=64), nullable=False),
    sa.Column('PatientName', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('PatientID')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_PatientName'), ['PatientName'], unique=False)

    op.create_table('study',
    sa.Column('StudyInstanceUID', sa.String(length=64), nullable=False),
    sa.Column('StudyDate', sa.DateTime(), nullable=True),
    sa.Column('StudyDescription', sa.String(length=64), nullable=True),
    sa.Column('PatientID', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['PatientID'], ['patient.PatientID'], ),
    sa.PrimaryKeyConstraint('StudyInstanceUID')
    )
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_StudyDate'), ['StudyDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_StudyDescription'), ['StudyDescription'], unique=False)

    op.create_table('series',
    sa.Column('SeriesInstanceUID', sa.String(length=64), nullable=False),
    sa.Column('SeriesDate', sa.DateTime(), nullable=True),
    sa.Column('SeriesDescription', sa.String(length=64), nullable=True),
    sa.Column('Modality', sa.String(length=64), nullable=True),
    sa.Column('metadata_fname', sa.Text(), nullable=True),
    sa.Column('PatientID', sa.String(length=64), nullable=True),
    sa.Column('StudyInstanceUID', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['PatientID'], ['patient.PatientID'], ),
    sa.ForeignKeyConstraint(['StudyInstanceUID'], ['study.StudyInstanceUID'], ),
    sa.PrimaryKeyConstraint('SeriesInstanceUID')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_Modality'), ['Modality'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_SeriesDate'), ['SeriesDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_SeriesDescription'), ['SeriesDescription'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_metadata_fname'), ['metadata_fname'], unique=False)

    op.create_table('instance',
    sa.Column('SOPInstanceUID', sa.String(length=64), nullable=False),
    sa.Column('SOPClassUID', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('PatientID', sa.String(length=64), nullable=True),
    sa.Column('StudyInstanceUID', sa.String(length=64), nullable=True),
    sa.Column('SeriesInstanceUID', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['PatientID'], ['patient.PatientID'], ),
    sa.ForeignKeyConstraint(['SeriesInstanceUID'], ['series.SeriesInstanceUID'], ),
    sa.ForeignKeyConstraint(['StudyInstanceUID'], ['study.StudyInstanceUID'], ),
    sa.PrimaryKeyConstraint('SOPInstanceUID')
    )
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instance_SOPClassUID'), ['SOPClassUID'], unique=False)
        batch_op.create_index(batch_op.f('ix_instance_filename'), ['filename'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.String(length=18), nullable=False),
    sa.Column('source_addr', sa.String(length=16), nullable=True),
    sa.Column('source_aet', sa.String(length=16), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('current_step', sa.String(length=32), nullable=True),
    sa.Column('current_step_filename', sa.Text(), nullable=True),
    sa.Column('status_msg', sa.Text(), nullable=True),
    sa.Column('expected_imgs', sa.Integer(), nullable=True),
    sa.Column('series', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['series'], ['series.SeriesInstanceUID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_destination',
    sa.Column('task_id', sa.String(length=18), nullable=True),
    sa.Column('device_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['device_name'], ['device.name'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], )
    )
    op.create_table('task_instance',
    sa.Column('task_id', sa.String(length=18), nullable=True),
    sa.Column('sop_instance_uid', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['sop_instance_uid'], ['instance.SOPInstanceUID'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_instance')
    op.drop_table('task_destination')
    op.drop_table('task')
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instance_filename'))
        batch_op.drop_index(batch_op.f('ix_instance_SOPClassUID'))

    op.drop_table('instance')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_metadata_fname'))
        batch_op.drop_index(batch_op.f('ix_series_SeriesDescription'))
        batch_op.drop_index(batch_op.f('ix_series_SeriesDate'))
        batch_op.drop_index(batch_op.f('ix_series_Modality'))

    op.drop_table('series')
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_StudyDescription'))
        batch_op.drop_index(batch_op.f('ix_study_StudyDate'))

    op.drop_table('study')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_PatientName'))

    op.drop_table('patient')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_port'))
        batch_op.drop_index(batch_op.f('ix_device_ae_title'))
        batch_op.drop_index(batch_op.f('ix_device_address'))

    op.drop_table('device')
    with op.batch_alter_table('app_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_app_log_module'))
        batch_op.drop_index(batch_op.f('ix_app_log_level'))
        batch_op.drop_index(batch_op.f('ix_app_log_function'))

    op.drop_table('app_log')
    # ### end Alembic commands ###
