"""Added stored_int column to series and studies

Revision ID: c2ceba845902
Revises: 2049032dc772
Create Date: 2024-08-09 10:59:10.402317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ceba845902'
down_revision = '2049032dc772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stored_in', sa.Text(), nullable=True))

    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stored_in', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.drop_column('stored_in')

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('stored_in')

    # ### end Alembic commands ###
