"""Added Radiopharmaceutical

Revision ID: c4bf16778663
Revises: 4a48dfc9f1dc
Create Date: 2024-08-22 11:04:26.657011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bf16778663'
down_revision = '4a48dfc9f1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radiopharmaceutical',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('synonyms', sa.Text(), nullable=True),
    sa.Column('half_life', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_radiopharmaceutical'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radiopharmaceutical')
    # ### end Alembic commands ###
