"""Added one-to-many relationship betweenTask and Series to represent the series originated as a processing result for each task

Revision ID: c8a25a0453d6
Revises: 281982dbeb1f
Create Date: 2023-08-12 12:49:28.810226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a25a0453d6'
down_revision = '281982dbeb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('originating_task', sa.String(length=18), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_series_originating_task_task'), 'task', ['originating_task'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_series_originating_task_task'), type_='foreignkey')
        batch_op.drop_column('originating_task')

    # ### end Alembic commands ###
