"""Added new columns to Task

Revision ID: c9d94c96760c
Revises: b1af1f6a71f6
Create Date: 2023-08-09 20:07:18.001197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d94c96760c'
down_revision = 'b1af1f6a71f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_destination', sa.Boolean(), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_msg', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('expected_imgs', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_task_current_step_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index('ix_task_current_step_filename', ['current_step_filename'], unique=False)
        batch_op.drop_column('expected_imgs')
        batch_op.drop_column('status_msg')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('is_destination')

    # ### end Alembic commands ###
