"""Added imgs column to Task

Revision ID: cf10e133bb6c
Revises: e850626ed9a2
Create Date: 2024-10-26 01:51:10.946659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf10e133bb6c'
down_revision = 'e850626ed9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imgs', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('imgs')

    # ### end Alembic commands ###
