"""Added model to FilterSettings

Revision ID: d2db1d8bcbf3
Revises: e56c30e141da
Create Date: 2024-03-18 18:28:10.687472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2db1d8bcbf3'
down_revision = 'e56c30e141da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter_settings', schema=None) as batch_op:
        batch_op.drop_column('model')

    # ### end Alembic commands ###
