"""Added noise blending parameter

Revision ID: e56c30e141da
Revises: ef935c3bd2a1
Create Date: 2024-03-14 10:16:20.743419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56c30e141da'
down_revision = 'ef935c3bd2a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('noise', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter_settings', schema=None) as batch_op:
        batch_op.drop_column('noise')

    # ### end Alembic commands ###
