"""Added series number to filter settings

Revision ID: ef935c3bd2a1
Revises: 6a0a3cd26016
Create Date: 2024-03-05 14:44:12.893302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef935c3bd2a1'
down_revision = '6a0a3cd26016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter_settings', schema=None) as batch_op:
        batch_op.drop_column('series_number')

    # ### end Alembic commands ###
